name: Backend CI

on:
  push:
    paths:
      - backend/**
  pull_request:
    paths:
      - backend/**

jobs:
  build-be:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
        - name: Checkout code
          uses: actions/checkout@v4.1.1
        
        - name: Set up Python
          uses: actions/setup-python@v5.0.0
          with:
            python-version: 3.11

        - name: Install Poetry
          run: |
              python3 -m pip install --upgrade pip
              pip3 install poetry
      
        - name: Install project dependencies
          run: poetry install

        - name: Lint code
          run: poetry run flake8
          continue-on-error: true

        # - name: Run tests
        #   run: |
        #         poetry run coverage run -m pytest
        #         poetry run coverage report